# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnPrincipalSM.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_vtnPrincipalSM(object):
    def setupUi(self, vtnPrincipalSM):
        if not vtnPrincipalSM.objectName():
            vtnPrincipalSM.setObjectName(u"vtnPrincipalSM")
        vtnPrincipalSM.resize(665, 490)
        self.centralwidget = QWidget(vtnPrincipalSM)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbBuscarCedula = QLabel(self.centralwidget)
        self.lbBuscarCedula.setObjectName(u"lbBuscarCedula")
        self.lbBuscarCedula.setGeometry(QRect(100, 40, 131, 16))
        self.txtBuscarCedula = QLineEdit(self.centralwidget)
        self.txtBuscarCedula.setObjectName(u"txtBuscarCedula")
        self.txtBuscarCedula.setGeometry(QRect(240, 40, 161, 22))
        self.txtBuscarCedula.setMaxLength(10)
        self.btnBuscar = QPushButton(self.centralwidget)
        self.btnBuscar.setObjectName(u"btnBuscar")
        self.btnBuscar.setGeometry(QRect(420, 40, 93, 28))
        self.lbNombre = QLabel(self.centralwidget)
        self.lbNombre.setObjectName(u"lbNombre")
        self.lbNombre.setGeometry(QRect(100, 70, 131, 16))
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(240, 70, 281, 22))
        self.txtNombre.setMaxLength(25)
        self.lbApellido = QLabel(self.centralwidget)
        self.lbApellido.setObjectName(u"lbApellido")
        self.lbApellido.setGeometry(QRect(100, 100, 131, 16))
        self.lbCedula = QLabel(self.centralwidget)
        self.lbCedula.setObjectName(u"lbCedula")
        self.lbCedula.setGeometry(QRect(100, 130, 131, 16))
        self.lbEdad = QLabel(self.centralwidget)
        self.lbEdad.setObjectName(u"lbEdad")
        self.lbEdad.setGeometry(QRect(100, 160, 131, 16))
        self.lbSexo = QLabel(self.centralwidget)
        self.lbSexo.setObjectName(u"lbSexo")
        self.lbSexo.setGeometry(QRect(100, 190, 131, 16))
        self.txtApellido = QLineEdit(self.centralwidget)
        self.txtApellido.setObjectName(u"txtApellido")
        self.txtApellido.setGeometry(QRect(240, 100, 281, 22))
        self.txtApellido.setMaxLength(25)
        self.txtCedula = QLineEdit(self.centralwidget)
        self.txtCedula.setObjectName(u"txtCedula")
        self.txtCedula.setGeometry(QRect(240, 130, 281, 22))
        self.txtCedula.setMaxLength(10)
        self.txtEdad = QLineEdit(self.centralwidget)
        self.txtEdad.setObjectName(u"txtEdad")
        self.txtEdad.setGeometry(QRect(240, 160, 281, 22))
        self.txtEdad.setMaxLength(3)
        self.cbSexo = QComboBox(self.centralwidget)
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.setObjectName(u"cbSexo")
        self.cbSexo.setGeometry(QRect(240, 190, 161, 22))
        self.btnAgregar = QPushButton(self.centralwidget)
        self.btnAgregar.setObjectName(u"btnAgregar")
        self.btnAgregar.setGeometry(QRect(100, 380, 93, 28))
        self.btnActualizar = QPushButton(self.centralwidget)
        self.btnActualizar.setObjectName(u"btnActualizar")
        self.btnActualizar.setGeometry(QRect(210, 380, 93, 28))
        self.btnEliminar = QPushButton(self.centralwidget)
        self.btnEliminar.setObjectName(u"btnEliminar")
        self.btnEliminar.setGeometry(QRect(320, 380, 93, 28))
        self.btnLimpiar = QPushButton(self.centralwidget)
        self.btnLimpiar.setObjectName(u"btnLimpiar")
        self.btnLimpiar.setGeometry(QRect(430, 380, 93, 28))
        self.lbEspecialidad = QLabel(self.centralwidget)
        self.lbEspecialidad.setObjectName(u"lbEspecialidad")
        self.lbEspecialidad.setGeometry(QRect(100, 220, 131, 16))
        self.lbFecha = QLabel(self.centralwidget)
        self.lbFecha.setObjectName(u"lbFecha")
        self.lbFecha.setGeometry(QRect(100, 280, 121, 16))
        self.lbTotalPagar = QLabel(self.centralwidget)
        self.lbTotalPagar.setObjectName(u"lbTotalPagar")
        self.lbTotalPagar.setGeometry(QRect(100, 340, 121, 16))
        self.txtFecha = QLineEdit(self.centralwidget)
        self.txtFecha.setObjectName(u"txtFecha")
        self.txtFecha.setGeometry(QRect(240, 280, 281, 22))
        self.txtFecha.setMaxLength(10)
        self.lbTipoUrgencia = QLabel(self.centralwidget)
        self.lbTipoUrgencia.setObjectName(u"lbTipoUrgencia")
        self.lbTipoUrgencia.setGeometry(QRect(100, 250, 131, 16))
        self.txtTotalPagar = QLineEdit(self.centralwidget)
        self.txtTotalPagar.setObjectName(u"txtTotalPagar")
        self.txtTotalPagar.setGeometry(QRect(240, 340, 281, 22))
        self.cbTipoUrgencia = QComboBox(self.centralwidget)
        self.cbTipoUrgencia.addItem("")
        self.cbTipoUrgencia.addItem("")
        self.cbTipoUrgencia.addItem("")
        self.cbTipoUrgencia.addItem("")
        self.cbTipoUrgencia.setObjectName(u"cbTipoUrgencia")
        self.cbTipoUrgencia.setGeometry(QRect(240, 250, 161, 22))
        self.lbHora = QLabel(self.centralwidget)
        self.lbHora.setObjectName(u"lbHora")
        self.lbHora.setGeometry(QRect(100, 310, 55, 16))
        self.txtHora = QLineEdit(self.centralwidget)
        self.txtHora.setObjectName(u"txtHora")
        self.txtHora.setGeometry(QRect(240, 310, 281, 22))
        self.txtHora.setMaxLength(5)
        self.txtEspecialidad = QLineEdit(self.centralwidget)
        self.txtEspecialidad.setObjectName(u"txtEspecialidad")
        self.txtEspecialidad.setGeometry(QRect(240, 220, 281, 22))
        self.txtEspecialidad.setMaxLength(25)
        vtnPrincipalSM.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(vtnPrincipalSM)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 665, 26))
        vtnPrincipalSM.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(vtnPrincipalSM)
        self.statusbar.setObjectName(u"statusbar")
        vtnPrincipalSM.setStatusBar(self.statusbar)

        self.retranslateUi(vtnPrincipalSM)

        QMetaObject.connectSlotsByName(vtnPrincipalSM)
    # setupUi

    def retranslateUi(self, vtnPrincipalSM):
        vtnPrincipalSM.setWindowTitle(QCoreApplication.translate("vtnPrincipalSM", u"MainWindow", None))
        self.lbBuscarCedula.setText(QCoreApplication.translate("vtnPrincipalSM", u"BUSCAR POR CEDULA: ", None))
        self.btnBuscar.setText(QCoreApplication.translate("vtnPrincipalSM", u"BUSCAR", None))
        self.lbNombre.setText(QCoreApplication.translate("vtnPrincipalSM", u"NOMBRE:", None))
        self.lbApellido.setText(QCoreApplication.translate("vtnPrincipalSM", u"APELLIDO:", None))
        self.lbCedula.setText(QCoreApplication.translate("vtnPrincipalSM", u"CEDULA:", None))
        self.lbEdad.setText(QCoreApplication.translate("vtnPrincipalSM", u"EDAD:", None))
        self.lbSexo.setText(QCoreApplication.translate("vtnPrincipalSM", u"SEXO:", None))
        self.cbSexo.setItemText(0, QCoreApplication.translate("vtnPrincipalSM", u"SELECCIONAR", None))
        self.cbSexo.setItemText(1, QCoreApplication.translate("vtnPrincipalSM", u"MASCULINO", None))
        self.cbSexo.setItemText(2, QCoreApplication.translate("vtnPrincipalSM", u"FEMENINO", None))

        self.btnAgregar.setText(QCoreApplication.translate("vtnPrincipalSM", u"AGREGAR", None))
        self.btnActualizar.setText(QCoreApplication.translate("vtnPrincipalSM", u"ACTUALIZAR", None))
        self.btnEliminar.setText(QCoreApplication.translate("vtnPrincipalSM", u"ELIMINAR", None))
        self.btnLimpiar.setText(QCoreApplication.translate("vtnPrincipalSM", u"LIMPIAR", None))
        self.lbEspecialidad.setText(QCoreApplication.translate("vtnPrincipalSM", u"ESPECIALIDAD:", None))
        self.lbFecha.setText(QCoreApplication.translate("vtnPrincipalSM", u"FECHA:", None))
        self.lbTotalPagar.setText(QCoreApplication.translate("vtnPrincipalSM", u"TOTAL A PAGAR:", None))
        self.lbTipoUrgencia.setText(QCoreApplication.translate("vtnPrincipalSM", u"TIPO DE URGENCIA:", None))
        self.cbTipoUrgencia.setItemText(0, QCoreApplication.translate("vtnPrincipalSM", u"SELECCIONAR", None))
        self.cbTipoUrgencia.setItemText(1, QCoreApplication.translate("vtnPrincipalSM", u"BAJA", None))
        self.cbTipoUrgencia.setItemText(2, QCoreApplication.translate("vtnPrincipalSM", u"MEDIA", None))
        self.cbTipoUrgencia.setItemText(3, QCoreApplication.translate("vtnPrincipalSM", u"ALTA", None))

        self.lbHora.setText(QCoreApplication.translate("vtnPrincipalSM", u"HORA:", None))
    # retranslateUi

